/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarForm: typeof import('./../components/CarForm.vue')['default']
    CarHero: typeof import('./../components/CarHero.vue')['default']
    CarTable: typeof import('./../components/CarTable.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./../components/display/UserAvatar.vue')['default']
  }
}
